pool:
  vmImage: 'Ubuntu 16.04'

variables:
  repository: "wk-j/pdf-library"

steps:

- script: |
    dotnet tool install -g Cake.Tool
  displayName: "Install tools"

# -- BUILD

- script: ~/.dotnet/tools/dotnet-cake -target=Pack
  displayName: 'Build with cake'

# -- PUBLISH

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '.publish/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: nuget.org

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    action: 'create'
    gitHubConnection: 'github.com'
    repositoryName: '$(repository)'
    title: $(Build.BuildNumber)
    tagSource: 'manual'
    tag: $(Build.BuildNumber)
    releaseNotesSource: input
    releaseNotes: ':rocket: $(Build.BuildNumber)'
    assets: '.publish/*.nupkg'
